#!/bin/bash

# Drop this file inside `/et/cron.houtly/` folder or just add a crontab to run this script every one hour:
# $ crontab -e
# @hourly /home/dietpi/checkWifiConnection
#
# Test it using `run-parts` (your script should be printed but not executed):
# $ run-parts --test /etc/cron.hourly

# Check connection
# NOTE: change 192.xxxx to your router IP address
if (( $(ping -c 1 192.168.0.1) != 0 )); then

    # Try to reconnect
    ifup wlan0
    ifdown wlan0
    
fi
